DROP TABLE IF EXISTS visits;
DROP TABLE IF EXISTS visitors;

CREATE TABLE visits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ip_address TEXT NOT NULL,
    visited TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE visitors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pseudo VARCHAR NOT NULL,
    ip_address TEXT NOT NULL,
    visited TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);